# Generated by Django 4.1.3 on 2022-12-04 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0003_alumnos_created_at_alumnos_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumnos',
            name='apellido',
            field=models.CharField(max_length=255, verbose_name='Apellido'),
        ),
        migrations.AlterField(
            model_name='alumnos',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creación'),
        ),
        migrations.AlterField(
            model_name='alumnos',
            name='email',
            field=models.EmailField(max_length=255, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='alumnos',
            name='nombre',
            field=models.CharField(max_length=255, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='alumnos',
            name='rut',
            field=models.CharField(max_length=12, unique=True, verbose_name='R.U.T'),
        ),
        migrations.AlterField(
            model_name='alumnos',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Actualización'),
        ),
    ]
